const control = (id, name, min, max, step, value, unit = '') => ({ id, name, min, max, step, value, unit });
const c = control;
const concord = 'https://mw.concord.org/nextgen/';
const polypad = 'https://polypad.amplify.com/';
const complexity = 'https://www.complexity-explorables.org/';
const falstad = 'https://www.falstad.com/mathphysics.html';
const biology = 'https://openstax.org/books/biology-2e/pages/5-2-passive-transport';
const circuits = 'https://openstax.org/books/college-physics-2e/pages/21-1-resistors-in-series-and-parallel';
const port = (id, title, subject, mode, sourceName, source, scientific, summary, controls, question, explanation, limit, challenge, tags = [subject]) => ({
  id, title, subject, mode, sourceName, source, scientific, summary, controls, question, explanation, limit, challenge, tags,
  portable: true, engine: 'three', implementation: 'Modelo, cena e texto próprios; adaptação didática da referência.',
  level: 'Fundamental II · Ensino médio', duration: '20–30 min',
});
export const portedLessons = [
  port('difusao', 'Uma gota encontra o caminho', 'biologia', 'diffusion', 'Concord Consortium', concord, biology,
    'Temperatura e permeabilidade mudam a mistura entre dois espaços.',
    [c('a','Temperatura',0,80,5,25,'°C'),c('b','Permeabilidade relativa',0,100,5,60,'%')],
    'No equilíbrio, as moléculas param de se mover?',
    'Dois compartimentos iguais começam com 100 e 0 mmol/L. O transporte reduz a diferença de concentração. Equilíbrio significa ausência de fluxo líquido, não ausência de movimento molecular.',
    'Dois volumes de 1 L, sem reação. Troca de primeira ordem: k = 0,05 × T/298,15 × permeabilidade; k hipotético em s⁻¹. Partículas representam a proporção, não trajetórias moleculares medidas.',
    'Compare dois ensaios no mesmo instante. Depois feche a membrana: o que deixa de mudar?', ['biologia','quimica']),
  port('osmose', 'A água atravessa, o soluto fica', 'biologia', 'osmosis', 'Concord Consortium', concord,
    'https://openstax.org/books/chemistry-2e/pages/11-4-colligative-properties',
    'Uma membrana seletiva separa dois reservatórios flexíveis.',
    [c('a','Soluto inicial à esquerda',10,100,5,80,'mmol/L'),c('b','Soluto inicial à direita',10,100,5,30,'mmol/L')],
    'A água vai para o lado inicialmente mais ou menos concentrado em soluto?',
    'Só a água atravessa. O lado com mais soluto recebe água e se dilui; o outro perde água e fica mais concentrado. As quantidades de soluto e o volume total permanecem constantes.',
    'Soluções ideais não dissociadas a 25 °C, 1 L inicial por lado. π = RTc. Ignora pressão hidrostática e elasticidade; aproxima a relaxação por 20 s, valor hipotético. Não representa uma célula real.',
    'Troque as concentrações entre os lados. Compare a direção e o volume após 20 s.', ['biologia','quimica']),
  port('reacoes', 'O calor muda a reação', 'quimica', 'reaction', 'Concord Consortium', concord,
    'https://openstax.org/books/chemistry-2e/pages/12-5-collision-theory',
    'Investigue concentração, temperatura e transformação de A em B.',
    [c('a','Concentração inicial de A',.25,3,.25,1,'mol/L'),c('b','Temperatura',10,60,5,25,'°C')],
    'Dobrar a concentração e aumentar a temperatura têm o mesmo efeito?',
    'Na reação hipotética A → B, A diminui exponencialmente. A temperatura altera a constante cinética pela relação de Arrhenius; a concentração inicial altera a quantidade e a taxa inicial.',
    'Primeira ordem, volume fixo, sem reação reversa. Ea = 25 kJ/mol e k a 25 °C = 0,03 s⁻¹ são assumidos para a aula. Esferas representam proporções, sem colisões atomísticas reais.',
    'Compare 25 e 50 °C com a mesma concentração e o mesmo tempo. Registre A e B.'),
  port('dna', 'Uma escada que guarda informação', 'biologia', 'dna', 'Concord Consortium', concord,
    'https://openstax.org/books/biology-2e/pages/14-2-dna-structure-and-sequencing',
    'Observe a complementaridade dos pares A–T e G–C em uma dupla hélice.',
    [c('a','Proporção desejada de G–C',0,100,10,50,'%'),c('b','Pares de bases',6,20,1,12)],
    'Trocar a composição muda o número de ligações entre as bases?',
    'A pareia com T; G com C. A–T tem duas ligações de hidrogênio; G–C tem três. Uma sequência curta exige arredondar a proporção desejada para um número inteiro de pares.',
    'Sequência sintética; dimensões e cores esquemáticas. Não simula genes, expressão, mutações ou estabilidade de uma molécula real. Rotação apenas ajuda a inspecionar.',
    'Mantenha o total de pares e compare duas composições. Conte as ligações e explique a diferença.', ['biologia','quimica']),
  port('fracoes', 'Partes menores, o mesmo inteiro', 'matematica', 'fractions', 'Polypad / Mathigon', polypad, polypad,
    'Subdivida as peças e construa frações equivalentes.',
    [c('a','Sextos preenchidos',1,6,1,3),c('b','Divisões de cada sexto',1,4,1,2)],
    'Cortar cada parte em duas muda a quantidade preenchida?',
    'A primeira barra tem seis partes iguais. A segunda subdivide cada parte. Numerador e denominador são multiplicados pelo mesmo número: a proporção preenchida permanece igual.',
    'Barras representam inteiros do mesmo tamanho. Não compara frações de inteiros diferentes; os controles têm valores inteiros.',
    'Represente 2/6 de três formas. Registre numeradores, denominadores e proporção.'),
  port('probabilidade', 'Prever não é adivinhar cada resultado', 'matematica', 'probability', 'Polypad / Mathigon', polypad, polypad,
    'Compare chance teórica e resultados de uma sequência de sorteios.',
    [c('a','Chance de sucesso',10,90,5,50,'%'),c('b','Quantidade de sorteios',20,120,10,60)],
    'Uma chance de 50% garante metade dos resultados em todo ensaio?',
    'O valor esperado é n × p. Uma sequência finita pode se afastar dele. As peças ficam verdes quando o sorteio é um sucesso, e laranja quando não é.',
    'Sorteios pseudoaleatórios com semente fixa para repetir a comparação, sem aposta ou previsão. Cada passo visual realiza um sorteio; a sequência não é reamostrada ao recomeçar.',
    'Avance até concluir os sorteios. Compare frequência observada e chance teórica em duas quantidades.'),
  port('balanca', 'O peso de uma incógnita', 'matematica', 'balance', 'Polypad / Mathigon', polypad, polypad,
    'Uma balança representa a equação a × x = b.',
    [c('a','Caixas iguais à esquerda',1,5,1,3),c('b','Peso total à direita',2,12,1,6,'unid.')],
    'Qual deve ser o peso de cada caixa para manter o equilíbrio?',
    'Todas as caixas guardam a mesma quantidade desconhecida. Dividir o peso da direita pelo número de caixas encontra x. A balança mostra a solução em equilíbrio.',
    'Equação positiva a × x = b; a solução é calculada automaticamente. Não simula dinâmica de uma balança nem ensina toda manipulação algébrica.',
    'Encontre três configurações em que cada caixa vale 2 unidades.'),
  port('funcoes', 'Uma reta conta uma história', 'matematica', 'function', 'GeoGebra', 'https://www.geogebra.org/', 'https://www.geogebra.org/',
    'Inclinação e intercepto mudam o gráfico de f(x) = ax + b.',
    [c('a','Inclinação a',-2,2,.25,1),c('b','Intercepto b',-3,3,.5,1)],
    'Duas retas com a mesma inclinação se cruzam?',
    'O coeficiente a determina a variação de f quando x aumenta uma unidade. O coeficiente b marca f(0). A reta representa a mesma regra para todos os pontos.',
    'Função afim em coordenadas relativas, com x entre −2 e 2. Eixos reescalados apenas na cena; valores numéricos preservados. Sem curva de ajuste a dados reais.',
    'Mantenha a inclinação e mude b. Depois mantenha b e inverta o sinal de a.'),
  port('predadores', 'Quando a comida também se multiplica', 'biologia', 'predator', 'Complexity Explorables', complexity, complexity,
    'Predadores e presas mudam juntos em um sistema de populações.',
    [c('a','Reprodução das presas',.2,1.2,.1,.6,'por unidade'),c('b','Mortalidade dos predadores',.2,1.2,.1,.5,'por unidade')],
    'Mais presas significam imediatamente mais predadores?',
    'O modelo Lotka–Volterra liga duas populações: presas crescem e são consumidas; predadores crescem ao consumir e diminuem por mortalidade. Os ciclos podem ter defasagem.',
    'Modelo contínuo, sem limite ambiental, migração ou indivíduos discretos. Início: 40 presas e 20 predadores; coeficientes de encontro 0,025 e conversão 0,02, assumidos. 1 s visual = 1 unidade de modelo; horizonte de 60 unidades. Símbolos resumem populações.',
    'Registre ambas as populações em 5, 10 e 20 unidades. Compare a ordem dos picos.', ['biologia','matematica']),
  port('bandos', 'De muitos movimentos nasce um bando', 'biologia', 'flock', 'Complexity Explorables', complexity, complexity,
    'Vizinhos alinham suas direções, enquanto o ruído dispersa o grupo.',
    [c('a','Ruído de direção',0,100,5,25,'%'),c('b','Raio de vizinhança',.3,2,.1,1.2,'unid.')],
    'Um grupo precisa de um líder para se alinhar?',
    'Cada agente usa a direção média dos vizinhos, somada a ruído. A regra local pode produzir movimento coletivo. O alinhamento mede quanto as direções concordam.',
    'Adaptação do modelo de Vicsek: 24 agentes, caixa periódica 6 × 4, velocidade 0,7 e passo 0,1, unidades relativas assumidas. Semente fixa; horizonte 60. Não simula anatomia, colisão ou voo real.',
    'Compare dois ruídos após 20 unidades, com o mesmo raio. Registre o alinhamento.', ['biologia','matematica']),
  port('transito-anel', 'Um engarrafamento sem semáforo', 'geografia', 'ringTraffic', 'Complexity Explorables', complexity, complexity,
    'Uma pequena freada se propaga em uma pista circular.',
    [c('a','Veículos no anel',8,28,1,20),c('b','Velocidade desejada',4,14,1,10,'m/s')],
    'Um congestionamento precisa de um obstáculo fixo?',
    'Motoristas reduzem a velocidade quando o espaço à frente diminui. Um veículo freia nos três primeiros segundos e libera a perturbação; observe a onda que circula pela pista.',
    'Seguimento hipotético, não previsão de tráfego: anel de 120 m, veículos de 3 m, resposta 0,8 s⁻¹ e velocidade segura = 0,6 × espaço livre. Passo 0,05 s, horizonte 60 s; sem ultrapassagens.',
    'Compare duas densidades à mesma velocidade desejada após 15 s.', ['geografia','fisica','historia']),
  port('realimentacao', 'O efeito que volta à causa', 'historia', 'feedback', 'LOOPY / Nicky Case', 'https://ncase.me/loopy/', 'https://ncase.me/loopy/',
    'Um retorno pode ampliar ou amortecer uma mudança inicial.',
    [c('a','Impulso inicial',.5,3,.25,1,'unid.'),c('b','Ganho do retorno',-.8,.8,.1,.3)],
    'Um efeito positivo no desenho é sempre bom para o sistema?',
    'A seta de retorno representa uma relação causal. Ganho positivo amplia o impulso; negativo o amortece. Os sinais descrevem a direção da influência, não um juízo de valor.',
    'Modelo linear x(t) = x₀ exp(g × t/5), unidades relativas; horizonte de 30 s. Não reproduz o editor LOOPY, não calibra economia ou comportamento e não implica crescimento ilimitado no mundo real.',
    'Compare retornos positivo, zero e negativo no mesmo instante.', ['historia','geografia','matematica']),
  port('ritmos', 'Divida o tempo e encontre um ritmo', 'artes', 'rhythm', 'Chrome Music Lab', 'https://musiclab.chromeexperiments.com/', polypad,
    'Distribua palmas em oito passos e altere o andamento.',
    [c('a','Palmas por ciclo',1,8,1,3),c('b','Andamento',60,180,5,100,'bpm')],
    'Acelerar o andamento muda a distribuição das palmas?',
    'Oito passos formam um ciclo. A distribuição espalha as palmas o mais regularmente possível; o andamento muda o tempo de cada passo. Ative o som para ouvir uma gravação real de palma.',
    'Sequenciador de oito passos, uma palma no máximo por passo; não é partitura completa. Som opcional: gravação CC0 de OwlishMedia. Prévias, avanço manual e impressão não produzem áudio.',
    'Compare 3 e 5 palmas em 100 bpm. Depois mantenha o padrão e mude só o andamento.', ['artes','matematica','educacao-fisica']),
  ...['series','parallel'].map(mode => port(mode === 'series' ? 'circuito-serie' : 'circuito-paralelo',
    mode === 'series' ? 'Um caminho para a corrente' : 'Dois caminhos para a corrente', 'fisica', mode, 'Falstad', falstad, circuits,
    mode === 'series' ? 'Dois resistores em série compartilham a corrente.' : 'Dois resistores em paralelo compartilham a tensão.',
    [c('a','Resistor A',10,100,5,30,'Ω'),c('b','Resistor B',10,100,5,60,'Ω')],
    mode === 'series' ? 'Qual resistor recebe a maior queda de tensão?' : 'Qual ramo recebe a maior corrente?',
    mode === 'series' ? 'Em série, a resistência equivalente é a soma. A corrente é a mesma e as quedas de tensão somam a tensão da bateria.' : 'Em paralelo, cada ramo recebe a tensão da bateria. A corrente total é a soma das correntes dos ramos.',
    'Bateria ideal de 12 V, resistores ôhmicos, sem capacitância, temperatura ou resistência dos fios. Pontos indicam corrente convencional com movimento desacelerado, não elétrons medidos.',
    'Dobre um resistor mantendo o outro. Compare resistência equivalente e corrente.', ['fisica','tecnologia'])),
  port('orbitas-elipticas', 'Perto do Sol, mais depressa', 'geografia', 'ellipse', 'NASA Eyes', 'https://science.nasa.gov/eyes/',
    'https://science.nasa.gov/learn/basics-of-space-flight/chapter3-1/',
    'Excentricidade e tamanho mudam uma órbita kepleriana.',
    [c('a','Semieixo maior',.5,3,.1,1,'UA'),c('b','Excentricidade',0,.8,.05,.4)],
    'O planeta percorre a elipse sempre na mesma velocidade?',
    'O Sol fica em um foco da elipse. A equação de Kepler determina a posição pelo tempo; o movimento fica mais rápido perto do periélio. O período depende do semieixo maior.',
    'Dois corpos, massa central igual à solar, órbita plana sem perturbações. 12 s visuais = 1 ano. T² = a³ em anos e UA; planeta sintético e tamanhos ampliados, sem dados vivos da NASA.',
    'Mantenha o semieixo e varie a excentricidade. Compare periélio, afélio e período.', ['geografia','fisica','matematica']),
  port('gps', 'Três distâncias encontram um lugar', 'tecnologia', 'gps', 'Bartosz Ciechanowski', 'https://ciechanow.ski/gps/', 'https://ciechanow.ski/gps/',
    'Observe a interseção das distâncias até três pontos conhecidos.',
    [c('a','Posição leste–oeste',-2,2,.1,.6,'km'),c('b','Posição norte–sul',-1.5,1.5,.1,.7,'km')],
    'Por que uma única distância não determina a posição?',
    'Uma distância define um círculo. Duas podem produzir duas posições; uma terceira referência ajuda a escolher uma. A leitura calcula as distâncias do receptor até três marcos fixos.',
    'Trilateração plana com distâncias exatas, não receptor GPS real. GPS 3D precisa tratar altitude, relógio, pseudodistâncias e pelo menos quatro satélites. Não usa posição do usuário.',
    'Mova o receptor mantendo a distância a um marco aproximadamente constante. Observe as outras.', ['tecnologia','geografia','matematica']),
  port('engrenagens', 'Dentes que trocam velocidade', 'fisica', 'gearPair', 'Bartosz Ciechanowski', 'https://ciechanow.ski/mechanical-watch/', 'https://ciechanow.ski/mechanical-watch/',
    'Duas engrenagens ligam o número de dentes à rotação.',
    [c('a','Dentes da motora',12,36,1,24),c('b','Dentes da movida',12,36,1,16)],
    'Uma engrenagem maior faz a outra girar mais rápido ou mais devagar?',
    'Dentes que se encontram passam na mesma taxa. A razão entre os números de dentes determina a rotação da movida, que gira no sentido oposto.',
    'Motora a 60 rpm, sem folga ou perdas; dentes esquemáticos, não perfil mecânico fabricável. Movimento desacelerado cinco vezes. Não modela torque ou relógio completo.',
    'Encontre duas combinações que produzam 120 rpm na movida.', ['fisica','matematica','tecnologia']),
  port('montanha-russa', 'A altura vira velocidade', 'fisica', 'coaster', 'myPhysicsLab', 'https://www.myphysicslab.com/roller/roller-single-en.html', 'https://www.myphysicslab.com/roller/roller-single-en.html',
    'Energia potencial e cinética se alternam em uma pista sem atrito.',
    [c('a','Altura máxima da pista',2,10,.5,6,'m'),c('b','Massa do carrinho',10,100,5,40,'kg')],
    'Um carrinho mais pesado fica mais rápido na mesma descida?',
    'A energia total é mgh no topo. Ao descer, potencial diminui e cinética aumenta. A velocidade ideal depende da diferença de altura, não da massa.',
    'Pista sinusoidal de 20 m, g = 9,81 m/s², sem atrito ou movimento de rotação. Início levemente após o topo com energia total mgh. Integra o deslocamento ao longo da pista; horizonte de 60 s.',
    'Compare duas massas no mesmo instante. Depois compare duas alturas.', ['fisica','matematica']),
  port('ressonancia-voz', 'Uma voz dentro de um tubo', 'portugues', 'resonance', 'Falstad', falstad, 'https://ciechanow.ski/sound/',
    'Comprimento e modo mudam as ressonâncias de uma coluna de ar.',
    [c('a','Comprimento do tubo',10,30,1,17,'cm'),c('b','Modo de ressonância',1,5,1,2)],
    'O comprimento de uma cavidade pode mudar seu som?',
    'Um tubo fechado em uma extremidade admite modos com frequências ímpares da fundamental. A forma ampliada mostra a onda estacionária de deslocamento do ar, com nó na ponta fechada.',
    'Tubo uniforme, som a 343 m/s e sem correção de extremidade; fₙ = (2n−1)c/(4L). Movimento desacelerado e ampliado, sem áudio. Não sintetiza vogais nem reproduz os formantes de um trato vocal real.',
    'Compare dois comprimentos no mesmo modo. Depois altere só o modo.', ['portugues','fisica','artes']),
];
